#sdk: "/Users/taudev/.rvm/gems/ruby-1.9.3-p551/gems/rhodes-5.5.0.14"
sdkversion: 5.5.0
name: ios_sni
version: 1.0
vendor: rhomobile
build: debug
applog: rholog.txt
javascript_application: true
iphone:
  configuration: Release
  sdk: iphonesimulator10.2
  #provisionprofile:
  #codesignidentity:
  #entitlements:
  BundleIdentifier: com.rhomobile.iossni
  BundleURLScheme: iossni
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"
  # Note: Specifies the URL schemes the app is able to call using Rho.System.runApplication
  #ApplicationQueriesSchemes: ["scheme1", "scheme2"]

  info_plist_data:
    NSAppTransportSecurity:
  #    NSAllowsArbitraryLoads: true
      NSExceptionDomains:
        badssl.com:
          NSIncludesSubdomains: true
          NSExceptionAllowsInsecureHTTPLoads: true
  #        NSTemporaryExceptionMinimumTLSVersion: 'TLSv1.0'
wp8:
  productid: '3046fd40-c4cf-0134-3c54-60f84732cfd8'
android:
  #manifest_template: 'AndroidManifest.erb'
  version: 4.1.0
  # Note: in order to simplify debugging only app messages and system channels with priority informative and higher, and any errors are enabled by default
  logcatFilter: APP:I StrictMode:I DEBUG:I *:E

wm:
  #sdk: "MC3000c50b (ARMV4I)"
  #sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"

win32:
  deployqt: 1
  deploymsvc: 1

extensions: []

rhobundle:
  exclude_items:
  - thumb.db
